version: "3.3"
services:
  # Zeppelin container
  docker-zeppelin:
    build: Zeppelin/
    container_name: docker-zeppelin
    ports:
    - 8080:8080 # Zeppelin
    network_mode: host
  # Zookeeper container
  docker-zookeeper:
    build: Zookeeper/
    container_name: docker-zookeeper
    environment:
    - ZOO_ID=1
    - ZOO_SERVERS=0.0.0.0
    ports:
    - 2181:2181 # Zookeeper
    network_mode: host
  # NiFi container
  docker-nifi:
    build: Nifi/
    container_name: docker-nifi
    environment:
    - NIFI_WEB_HTTP_PORT=8080
    - NIFI_CLUSTER_IS_NODE=true
    - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
    - NIFI_ZK_CONNECT_STRING=localhost:2181
    - NIFI_ELECTION_MAX_WAIT=1 min
    ports:
    - 8080:8980 # Nifi
    network_mode: host
  # Superset container
  docker-superset:
    build: Superset/
    container_name: docker-superset
    environment:
    - MAPBOX_API_KEY=${MAPBOX_API_KEY}
    ports:
    - 8088:8088 # Superset
    network_mode: host
  # Kafka container
  docker-kafka:
    build: Kafka/
    container_name: docker-kafka
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
    - KAFKA_ADVERTISED_HOST_NAME=localhost
    - AUTO_CREATE_TOPICS=false
    - KAFKA_CREATE_TOPICS=divolte:4:1
    ports:
    - 9092:9092 # Kafka broker
    network_mode: host
    depends_on:
    - docker-zookeeper
  # Postgres container
  docker-postgres:
    build: Postgres/
    container_name: docker-postgres
    environment:
    - PG_PASSWORD=TCrGaanoC2s7gT
    - DB_NAME=druid
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    ports:
    - 5432:5432 # postgres
    network_mode: host
  # Druid-coordinator container
  docker-druid-coordinator:
    build: Druid/
    container_name: docker-druid-coordinator
    environment:
    - DRUID_XMX=1g
    - DRUID_XMS=1g
    - DRUID_MAXNEWSIZE=250m
    - DRUID_NEWSIZE=250m
    command:
    - coordinator
    ports:
    - 8081:8081 # coordinator
    network_mode: host
    depends_on:
    - docker-zookeeper
    - docker-postgres
  # Druid-overlord container
  docker-druid-overlord:
    build: Druid/
    container_name: docker-druid-overlord
    environment:
    - DRUID_XMX=1g
    - DRUID_XMS=1g
    - DRUID_MAXNEWSIZE=250m
    - DRUID_NEWSIZE=250m
    command:
    - overlord
    ports:
    - 8090:8090 # overlord
    network_mode: host
    depends_on:
    - docker-zookeeper
    - docker-postgres
    - docker-druid-coordinator
  # Druid-overlord container
  docker-druid-historical:
    build: Druid/
    container_name: docker-druid-historical
    environment:
    - DRUID_XMX=1g
    - DRUID_XMS=1g
    - DRUID_MAXNEWSIZE=250m
    - DRUID_NEWSIZE=250m
    command:
    - historical
    ports:
    - 8083:8083 # historical
    network_mode: host
    depends_on:
    - docker-zookeeper
    - docker-postgres
    - docker-druid-coordinator
    - docker-druid-overlord
  # Druid-overlord container
  docker-druid-middlemanager:
    build: Druid/
    container_name: docker-druid-middlemanager
    environment:
    - DRUID_XMX=1g
    - DRUID_XMS=1g
    - DRUID_MAXNEWSIZE=250m
    - DRUID_NEWSIZE=250m
    command:
    - middleManager
    ports:
    - 8091:8091 # middleManager
    network_mode: host
    depends_on:
    - docker-zookeeper
    - docker-postgres
    - docker-druid-coordinator
    - docker-druid-overlord
    - docker-druid-historical
  # Druid-overlord container
  docker-druid-broker:
    build: Druid/
    container_name: docker-druid-broker
    environment:
    - DRUID_XMX=1g
    - DRUID_XMS=1g
    - DRUID_MAXNEWSIZE=250m
    - DRUID_NEWSIZE=250m
    command:
    - broker
    ports:
    - 8082:8082 # broker
    network_mode: host
    depends_on:
    - docker-zookeeper
    - docker-postgres
    - docker-druid-coordinator
    - docker-druid-overlord
    - docker-druid-historical
    - docker-druid-middlemanager